### ISSUE TITLE
Create Graphs and Visualization on Dashboard

### ISSUE THREAD

**Issue by muzammil65** [DEXDEVS/ic-school#13]
For Attendance of employees and students
(Separately for students and Employees.)
For Fee Detail
For Income Graphs and Expenses Graphs Visualization.

**Comment by ranafaraz** [comment]
practically/yii2-chartjs
USER INTERFACE  
Chart js wrapper for yii2 to help with rendering data charts

**Comment by AnasShafqat** [comment]
For Fee Detail,
For Income Graphs and Expenses Graphs Visualization are embedded.
