### ISSUE TITLE
Status b/w 'Status' & 'Academic Status' in STD Profile?

### ISSUE THREAD

**Issue by ranafaraz** [DEXDEVS/ic-school#46]
![image](https://user-images.githubusercontent.com/26284885/73785056-64dd4a00-47b8-11ea-9f2b-d23d9dbffa5c.png)

**Comment by AnasShafqat** [comment]
Over all status of student is belongs to Status i.e: Active & Inactive
Academic status of student is belongs to Academic Status i.e: Enrolled, Promoted, Struck-Off, Left
