### ISSUE TITLE
Why Admission Date, Session, Section are not being displayed in STD Profile?

### ISSUE THREAD

**Issue by ranafaraz** [DEXDEVS/ic-school#47]
![image](https://user-images.githubusercontent.com/26284885/73785224-b8e82e80-47b8-11ea-8225-7e292a39d50e.png)

**Comment by ranafaraz** [comment]
Replace N/A with 'Not Enrolled Yet'.

**Comment by AnasShafqat** [comment]
Because student is not enrolled yet.

**Comment by AnasShafqat** [comment]
Replaced N/A with 'Not Enrolled Yet'
